=== robpvn/Speidermerker-XML/Speidermerker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bygdoyspeider.net/Speidermerker" elementFormDefault="qualified" xmlns:spm="http://www.bygdoyspeider.net/Speidermerker">


    
    <include schemaLocation=""></include>
    <complexType name="ProgramMerke">
    	<sequence>
    		<element name="Navn" type="string"></element>
            <element name="Beskrivelse" type="string"></element>
            <element name="MerkeBildeUrl" type="string"></element>
    		<element name="AntallMålSomSkalNås">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="ProgramMål" type="spm:ProgramMål"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>

    	</sequence>
    </complexType>
    
    
    <complexType name="Mål">
    	<sequence>
    		<element name="Kode" type="spm:MålKode" maxOccurs="1" minOccurs="1"></element>
            <element name="MålKategori" type="spm:MålKategori" maxOccurs="1" minOccurs="1">
    		</element>
            <element name="Beskrivelse" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="MålDeler" type="spm:MålDeler"
            	maxOccurs="1" minOccurs="1">
            </element>
            
        </sequence>
    </complexType>
    

    <complexType name="FordypningsMerke">
        <sequence>
    		<element name="Navn" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="Beskrivelse" type="string" maxOccurs="1" minOccurs="1">
    		</element>
            <element name="MerkeBildeUrl" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="Begrunnelse" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="EkstraInfo" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="MerkeType" type="spm:MerkeType" maxOccurs="1" minOccurs="1"></element>
    		<element name="BidrarTil" type="spm:MålKoder" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Oppgaver" type="spm:Oppgaver" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="AntallSelvValgteOppgaver" type="int" maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="Oppgave">
    	<sequence>
    		<element name="DelOppgaver" type="spm:DelOppgaver"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="AntallDelOppgaverSomSkalUtføres"
    			maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>
    




    <complexType name="SpeiderMerke">
    	<sequence>

    		<element name="BeverMerker" type="spm:BeverMerker"></element>
    		<element name="SmåspeiderMerker"
    			type="spm:SmåspeiderMerker">
    		</element>
    		<element name="StifinnerMerker"
    			type="spm:StifinnerMerker">
    		</element>
    		<element name="VandrerMerker" type="spm:VandrerMerker"></element>
    		<element name="RoverMerker" type="spm:RoverMerker"></element>
    	</sequence>
    </complexType>

    <element name="SpeiderMerker" type="spm:SpeiderMerke"></element>

    <complexType name="ProgramMerker">
    	<sequence>
    		<element name="ProgramMerke" type="spm:ProgramMerke" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="FordypningsMerker">
    	<sequence>
    		<element name="FordypningsMerke"
    			type="spm:FordypningsMerke" maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <simpleType name="MålKode">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="BeverMerker">
    	<sequence>
    		<element name="ProgramMerker" type="spm:ProgramMerker"></element>
    		<element name="JegErBeredtMerke" type="spm:JegErBeredtMerke" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="SmåspeiderMerker">
    	<sequence>
    		<element name="ProgramMerker" type="spm:ProgramMerker"></element>
    		<element name="FordypningsMerker"
    			type="spm:FordypningsMerker">
    		</element>
    		<element name="JegErBeredtMerke" type="spm:JegErBeredtMerke" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="StifinnerMerker">
    	<sequence>
    		<element name="ProgramMerker" type="spm:ProgramMerker"></element>
    		<element name="FordypningsMerker"
    			type="spm:FordypningsMerker">
    		</element>
    		<element name="JegErBeredtMerke" type="spm:JegErBeredtMerke" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="VandrerMerker">
    	<sequence>
    		<element name="ProgramMerker" type="spm:ProgramMerker"></element>
    		<element name="FordypningsMerker"
    			type="spm:FordypningsMerker">
    		<element name="JegErBeredtMerke" type="spm:JegErBeredtMerke" maxOccurs="1" minOccurs="1"></element>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="RoverMerker">
    	<sequence>
    		<element name="ProgramMerker" type="spm:ProgramMerker"></element>
    		<element name="FordypningsMerker"
    			type="spm:FordypningsMerker">
    		<element name="JegErBeredtMerke" type="spm:JegErBeredtMerke" maxOccurs="1" minOccurs="1"></element>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="ProgramMål">
    	<sequence>
    		<element name="Mål" type="spm:Mål" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="MålDeler">
    	<sequence>
    		<element name="DelMål" type="spm:DelMål" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <simpleType name="DelMål">
    	<restriction base="string"></restriction>
    </simpleType>

    <simpleType name="MålKategori">
    	<restriction base="string"></restriction>
    </simpleType>

    <simpleType name="DelOppgave">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="DelOppgaver">
    	<sequence>
    		<element name="DelOppgave" type="spm:DelOppgave" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="Oppgaver">
    	<sequence>
    		<element name="Oppgave" type="spm:Oppgave" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <simpleType name="MerkeType">
    	<restriction base="string">
    		<enumeration value="Speider"></enumeration>
    		<enumeration value="Patrulje"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="JegErBeredtMerke">
		<sequence>
    		<element name="Navn" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="Beskrivelse" type="string" maxOccurs="1" minOccurs="1">
    		</element>
            <element name="MerkeBildeUrl" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="Begrunnelse" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="EkstraInfo" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="BidrarTil" type="spm:MålKode" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="Oppgaver" type="spm:Oppgaver" maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="MålKoder">
    	<sequence>
    		<element name="MålKode" type="spm:MålKode" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== robpvn/Speidermerker-XML/XML/Speidermerker.xml
<?xml version="1.0" encoding="utf-8"?>
<spm:SpeiderMerker xmlns:spm="http://www.bygdoyspeider.net/Speidermerker" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bygdoyspeider.net/Speidermerker Speidermerker.xsd ">
  <spm:BeverMerker>
    <spm:ProgramMerker>
      <spm:ProgramMerke>
        <spm:Navn>Friluftsliv</spm:Navn>
        <spm:Beskrivelse>Hensikten med dette merket er at speiderne skal:

    Utvikle sanseapparat, motorikk og fysisk form til et tilfredsstillende nivå i forhold til egne forutsetninger.
    Bli glad i naturen.
    Få kjennskap til naturen og ferdes i den til alle årstider.
	</spm:Beskrivelse>
        <spm:MerkeBildeUrl>images/Friluftsliv_Bever.gif</spm:MerkeBildeUrl>
        <spm:AntallMålSomSkalNås>8</spm:AntallMålSomSkalNås>
        <spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-1</spm:Kode>
            <spm:MålKategori>Friluftsferdigheter</spm:MålKategori>
            <spm:Beskrivelse>Få nye turerfaringer fra alle årstider.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Delta i sesongbestemte aktiviteter som ski, bading eller blomsterplukking.</spm:DelMål>
              <spm:DelMål>Være med på to dagsturer.</spm:DelMål>
              <spm:DelMål>Være på utemøter i alle årstider.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-2</spm:Kode>
            <spm:MålKategori>Friluftsferdigheter</spm:MålKategori>
            <spm:Beskrivelse>Utvikle gode ferdigheter innen orientering.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Kjenne igjen de viktigste karttegnene som vann, myr, sti og vei.</spm:DelMål>
              <spm:DelMål>Kjenne de fire himmelretningene.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-3</spm:Kode>
            <spm:MålKategori>Friluftsferdigheter</spm:MålKategori>
            <spm:Beskrivelse>Utvikle kunnskap om og erfaring med ulike overnattingsformer.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Kjenne til forskjellige overnattingsformer som telt, lavvo og gapahuk.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-4</spm:Kode>
            <spm:MålKategori>Friluftsferdigheter</spm:MålKategori>
            <spm:Beskrivelse>Utvikle kunnskap om og erfaring med matlaging på ulike varmekilder.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Spise mat laget på bål, primus, i kokegrop eller på stormkjøkken.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-5</spm:Kode>
            <spm:MålKategori>Friluftsferdigheter</spm:MålKategori>
            <spm:Beskrivelse>Utvikle gode ferdigheter for bruk av bål og åpen ild</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Hjelpe til med å lage et bål.</spm:DelMål>
              <spm:DelMål>Kjenne til, og følge, regler for oppførsel ved bålet, og forstå hvorfor vi har disse reglene.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-6</spm:Kode>
            <spm:MålKategori>Naturkjennskap</spm:MålKategori>
            <spm:Beskrivelse>Utvikle forståelse for friluftslivets verdier og betydning for samfunnet.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Finne ut hvorfor det er bra å være i ute i naturen.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-7</spm:Kode>
            <spm:MålKategori>Naturkjennskap</spm:MålKategori>
            <spm:Beskrivelse>Utvikle forståelse for hvordan politiske beslutninger kan påvirke friluftslivet.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Kjenne til regler for hvordan mennesker skal ta vare på naturen, for eksempel hva vi skal gjøre med søppel på tur, eller hvorfor vi ikke kan kjøre bil og motorsykkel i utmark.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-8</spm:Kode>
            <spm:MålKategori>Naturkjennskap</spm:MålKategori>
            <spm:Beskrivelse>Utvikle kunnskap knyttet til lokal og nasjonal natur.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Ha kunnskap om hvordan mennesker bruker naturen, for eksempel i jordbruk.</spm:DelMål>
              <spm:DelMål>Se på fem blomster eller trær og fem dyr, og lære seg navnet på disse.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-9</spm:Kode>
            <spm:MålKategori>Naturkjennskap</spm:MålKategori>
            <spm:Beskrivelse>Få erfaring med ferdsel i ulike naturmiljø og utforsking av ukjente områder.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Utforske et sted de ikke har vært på før.</spm:DelMål>
              <spm:DelMål>Være på turer og møter hvor de ser på naturtyper som er vanlige i nærmiljøet deres, som skog, fjell, eng og skjærgård.  </spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-10</spm:Kode>
            <spm:MålKategori>Naturkjennskap</spm:MålKategori>
            <spm:Beskrivelse>Oppleve stemninger og skjønnhet i naturen, både alene og sammen med andre.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Se døgnet skifte og oppleve for eksempel stjernehimmel, solnedgang og soloppgang eller skyer i vinden.</spm:DelMål>
              <spm:DelMål>Finne noe fint eller uvanlig i naturen.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-11</spm:Kode>
            <spm:MålKategori>Naturkjennskap</spm:MålKategori>
            <spm:Beskrivelse>Utvikle kunnskap om og erfaring med bruk av ikke-motoriserte framkomstmidler.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Vite hvordan de  kan komme seg fram uten å gå eller bruke motor og prøve å bevege seg i naturen med for eksempel sykkel, ski eller robåt.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-12</spm:Kode>
            <spm:MålKategori>Førstehjelp og sikkerhet</spm:MålKategori>
            <spm:Beskrivelse>Utvikle gode rutiner for turplanlegging.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Være med på å pakke en dagstursekk.</spm:DelMål>
              <spm:DelMål>Vite hvilke klær de skal ha på til ulike årstider.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-13</spm:Kode>
            <spm:MålKategori>Førstehjelp og sikkerhet</spm:MålKategori>
            <spm:Beskrivelse>Utvikle kunnskap og erfaring innen forebygging og håndtering av ulykker.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Kunne skaffe hjelp ved en ulykke.</spm:DelMål>
              <spm:DelMål>Kunne nummeret til sykebil, politi og brannvesen.</spm:DelMål>
              <spm:DelMål>Kunne knivreglene, og følge dem.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-14</spm:Kode>
            <spm:MålKategori>Førstehjelp og sikkerhet</spm:MålKategori>
            <spm:Beskrivelse>Utvikle og vedlikeholde ferdigheter innen førstehjelp.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Kunne rense sår og vite hvorfor det gjøres.</spm:DelMål>
              <spm:DelMål>Kunne sette på plaster og behandle sår og småskader. </spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>F-15</spm:Kode>
            <spm:MålKategori>Førstehjelp og sikkerhet</spm:MålKategori>
            <spm:Beskrivelse>Utvikle kunnskap om bruk og vedlikehold av turutstyr.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Holde orden på kniven: Passe på at kniven har hel slire, passe på at kniven legges i slira etter bruk, passe på at kniven ikke ligger på bakken.</spm:DelMål>
            </spm:MålDeler>
          </spm:ProgramMål>
        </spm:ProgramMål>
      </spm:ProgramMerke>
      <spm:ProgramMerke>
        <spm:Navn>Samfunnsengasjement</spm:Navn>
        <spm:Beskrivelse>Fellesskap gjør sterk!
Det er nok den viktigste grunnen til at vi danner samfunn. Vi slår oss sammen med likesinnede. Når vi er mange kan vi klare ting som vi ellers ikke ville klart. For at et samfunn skal fungere er det viktig at alle yter noe, og at alle bidrar på en positiv måte.

Det å være samfunnsengasjert er å engasjere seg og bidra i de samfunn du ferdes i/tilhører på en positiv måte. Speiderloven gir gode retningslinjer for hva speidere kan gjøre.

Hensikten med dette merket er at speiderne skal:

    Få mulighet til medbestemmelse og trening i å ytre egne meninger.
    Få forståelse for andre menneskers livssituasjon, bakgrunn og synspunkter.
    Delta aktivt i å utvikle samfunnet positivt.</spm:Beskrivelse>
        <spm:MerkeBildeUrl>images/samfunnsengasjement_bever.gif</spm:MerkeBildeUrl>
        <spm:AntallMålSomSkalNås>5</spm:AntallMålSomSkalNås>
        <spm:ProgramMål>
          <spm:ProgramMål>
            <spm:Kode>S-1</spm:Kode>
            <spm:MålKategori>Demokrati og deltagelse</spm:MålKategori>
            <spm:Beskrivelse>Bli kjent med demokratiske verdier, og bruk din rett til medbestemmelse.</spm:Beskrivelse>
            <spm:MålDeler>
              <spm:DelMål>Være med på å bestemme en aktivitet eller lek beverkolonien skal utføre.</spm:DelMål>
